version: 2.1

orbs:
  node: circleci/node@4.5

jobs:
  build:
    executor:
      name: node/default
      
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build
          
  deploy:
    executor:
      name: node/default
    
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm    
      - run:
          command: ssh deploy server # 部署命令
          
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
